rooms:
  - id: attic1
    names:
    - poddasze sekcja lewa
    - poddasze część lewa
    devices:
      - id: A1
        deviceType: lamp
        functions:
        - turnOn
        - turnOff
        position:
        - na suficie
        - u sufitu
        - na górze
        - u góry
      - id: A2
        deviceType: lamp
        functions:
        - turnOn
        - turnOff
        position:
        - na biurku
      - id: A3
        deviceType: radio
        functions:
        - turnOn
        - turnOff
        - setChannel
        - next
        - prev
        - setVolume
        - volumeUp
        - volumeDown
        - mute
      - id: A4
        deviceType: computer
        functions:
          - turnOn
          - turnOff
      - id: A5
        deviceType: monitor
        functions:
          - turnOn
          - turnOff
  - id: attic2
    names:
    - poddasze sekcja prawa
    - poddasze część prawa
    devices:
    - id: A6
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - na suficie
      - u sufitu
      - na górze
      - u góry
    - id: A7
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - nad ławą
    - id: A8
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - lewa
    - id: A9
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - prawa
    - id: A10
      deviceType: tv
      functions:
      - turnOn
      - turnOff
      - setChannel
      - next
      - prev
      - setVolume
      - volumeUp
      - volumeDown
      - mute
    - id: A11
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - za telewizorem
  - id: attic
    names:
    - poddasze
    devices:
    - id: A12
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
  - id: bedroom
    names:
    - sypialnia
    devices:
    - id: B1
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      - temperatureWarm
      - temperatureCold
      position:
      - na suficie
      - u sufitu
      - na górze
      - u góry
    - id: B2
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - lewa
    - id: B3
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - prawa
    - id: B4
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - nocna
    - id: B5
      deviceType: tv
      functions:
      - turnOn
      - turnOff
      - setChannel
      - next
      - prev
      - setVolume
      - volumeUp
      - volumeDown
      - mute
    - id: B6
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - za telewizorem
    - id: B7
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
    - id: B8
      deviceType: alarm
      functions:
      - turnOn
      - turnOff
      - setAlarmTime
  - id: bathroom
    names:
    - łazienka
    devices:
    - id: C1
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - na suficie
      - u sufitu
      - na górze
      - u góry
    - id: C2
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - nad lustrem
    - id: C3
      deviceType: fan
      functions:
      - turnOn
      - turnOff
    - id: C4
      deviceType: blower
      functions:
      - turnOn
      - turnOff
    - id: C5
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
  - id: salon
    names:
    - salon
    devices:
    - id: D1
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - na suficie
      - u sufitu
      - na górze
      - u góry
    - id: D2
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      - setColor
      position:
      - lewa
    - id: D3
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      - setColor
      position:
      - prawa
    - id: D4
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
    - id: D5
      deviceType: curtain
      functions:
      - up
      - down
      - stop
      position:
      - lewa
    - id: D6
      deviceType: curtain
      functions:
      - up
      - down
      - stop
      position:
      - prawa
    - id: D7
      deviceType: curtain
      functions:
      - up
      - down
      - stop
  - id: kitchen
    names:
    - kuchnia
    devices:
    - id: E1
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - na suficie
      - u sufitu
      - na górze
      - u góry
    - id: E2
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      - setBrightness
      position:
      - nad szafkami
    - id: E3
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - pod szafkami
    - id: E4
      deviceType: lamp
      functions:
      - turnOn
      - turnOff
      position:
      - okap
    - id: E5
      deviceType: cookerHood
      functions:
      - turnOff
      - faster
      - slower
    - id: E6
      deviceType: fan
      functions:
      - turnOn
      - turnOff
    - id: E7
      deviceType: lamp
      functions:
      - turnOn
      - turnOff

devices:
  - id: lamp
    names:
    - lampa
    - światło
    - oświetlenie
  - id: radio
    names:
    - radio
  - id: computer
    names:
    - komputer
  - id: monitor
    names:
    - monitor
  - id: tv
    names:
    - telewizor
  - id: cookerHood
    names:
    - okap
  - id: fan
    names:
    - wentylator
  - id: blower
    names:
    - dmuchawa
  - id: curtain
    names:
    - zasłona
    - żaluzja
  - id: alarm
    names:
    - budzik
    - alarm

functions:
  - id: turnOn
    names:
    - włącz
    - załącz
    - zapal
    command: on ID
  - id: turnOff
    names:
    - wyłącz
    - zgaś
    command: off ID
  - id: setChannel
    names:
    - zmień
    - wybierz
    - przełącz
    parameter: INT
    command: set ID ch INT
  - id: next
    names:
    - następny
    - dalej
    - kolejny
    command: set ID ch_next
  - id: prev
    names:
    - poprzedni
    - wstecz
    - cofnij
    command: set ID ch_prev
  - id: volumeUp
    names:
    - podgłośnij
    command: set ID vol_up
  - id: volumeDown
    names:
    - ścisz
    - przycisz
    command: set ID vol_down
  - id: setVolume
    names:
    - głośność
    parameter: INT
    command: set ID vol INT
  - id: mute
    names:
    - wycisz
    command: set ID vol mute
  - id: temperatureWarm
    names:
    - barwa ciepła
    command: set ID temp warm
  - id: temperatureCold
    names:
    - barwa zimna
    command: set ID temp cold
  - id: setBrightness
    names:
    - ustaw jasność
    parameter: INT
    command: set ID br INT
  - id: setColor
    names:
    - ustaw kolor
    parameter: COLOR
    command: set ID color COLOR
  - id: setAlarmTime
    names:
    - ustaw budzik
    - ustaw alarm
    parameter: INT_GG, INT_MM
    command: set ID time INT_GG:INT_MM
  - id: up
    names:
    - do góry
    - w górę
    - podnieś
    command: up ID
  - id: down
    names:
    - w dół
    - opuść
    command: down ID
  - id: stop
    names:
    - stop
    - zatrzymaj
    command: stop ID
  - id: faster
    names:
    - szybciej
    - zwiększ obroty
    command: fast ID
  - id: slower
    names:
    - wolniej
    - zmniejsz obroty
    command: slow ID
